    - include: configure-hostname.yml
    - include: keys-deploy.yml

    - include: debian-install.yml
      when: ansible_distribution == 'Debian'

    - include: centos-install.yml
      when: ansible_distribution == 'CentOS'

    - include: configure-zram.yml
      when:
        - ansible_virtualization_role == 'guest'
        - ansible_virtualization_type != 'lxc'
        - ansible_virtualization_type != 'openvz'

    - include: set-locale.yml
      when:
        - ansible_distribution == 'Debian'

    - include: common-confs.yml

    - include: configure-sshd.yml
      tags: ssh
